# nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["corepack enable"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"