# nixpacks.toml

[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = ["npx pnpm@10.29.3 install --frozen-lockfile"]

[phases.build]
cmds = [
  "NODE_OPTIONS='--max-old-space-size=1024' npm run build",
  "cp -r public .next/standalone/",
  "cp -r .next/static .next/standalone/.next/",
]

[start]
cmd = "NODE_OPTIONS='--max-old-space-size=256 --max-semi-space-size=16' node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "24"
HOSTNAME = "0.0.0.0"
